-- This file is generated from wezterm.tera by Whiskers. Do not edit by hand.
--
-- It is the palette data the plugin turns into WezTerm color schemes; run
-- `just build` after the evergarden palette changes.
return {
  -- Flavors in cycle order.
  order = { 'winter', 'fall', 'spring', 'summer' },

  -- Accent colors in cycle order. Every flavor defines all of these.
  accents = { 'red', 'orange', 'yellow', 'lime', 'green', 'aqua', 'skye', 'snow', 'blue', 'purple', 'pink', 'cherry' },

  flavors = {
    winter = {
      name = 'Winter',
      dark = true,
      colors = {
        red = '#f57f82',
        orange = '#f7a182',
        yellow = '#f5d098',
        lime = '#dbe6af',
        green = '#cbe3b3',
        aqua = '#b3e3ca',
        skye = '#b3e6db',
        snow = '#afd9e6',
        blue = '#b2caed',
        purple = '#d2bdf3',
        pink = '#f3c0e5',
        cherry = '#fae6ef',
        text = '#f8f9e8',
        subtext1 = '#adc9bc',
        subtext0 = '#96b4aa',
        overlay2 = '#839e9a',
        overlay1 = '#6f8788',
        overlay0 = '#58686d',
        surface2 = '#4a585c',
        surface1 = '#374145',
        surface0 = '#262f33',
        base = '#1e2528',
        mantle = '#191e21',
        crust = '#171c1f',
      },
    },
    fall = {
      name = 'Fall',
      dark = true,
      colors = {
        red = '#f57f82',
        orange = '#f7a182',
        yellow = '#f5d098',
        lime = '#dbe6af',
        green = '#cbe3b3',
        aqua = '#b3e3ca',
        skye = '#b3e6db',
        snow = '#afd9e6',
        blue = '#b2caed',
        purple = '#d2bdf3',
        pink = '#f3c0e5',
        cherry = '#fae6ef',
        text = '#f8f9e8',
        subtext1 = '#adc9bc',
        subtext0 = '#96b4aa',
        overlay2 = '#839e9a',
        overlay1 = '#6f8788',
        overlay0 = '#58686d',
        surface2 = '#4a585c',
        surface1 = '#374145',
        surface0 = '#2b3337',
        base = '#232a2e',
        mantle = '#1c2225',
        crust = '#171c1f',
      },
    },
    spring = {
      name = 'Spring',
      dark = true,
      colors = {
        red = '#f57f82',
        orange = '#f7a182',
        yellow = '#f5d098',
        lime = '#dbe6af',
        green = '#cbe3b3',
        aqua = '#b3e3ca',
        skye = '#b3e6db',
        snow = '#afd9e6',
        blue = '#b2caed',
        purple = '#d2bdf3',
        pink = '#f3c0e5',
        cherry = '#fae6ef',
        text = '#f8f9e8',
        subtext1 = '#adc9bc',
        subtext0 = '#96b4aa',
        overlay2 = '#839e9a',
        overlay1 = '#6f8788',
        overlay0 = '#58686d',
        surface2 = '#4a585c',
        surface1 = '#3e4a4f',
        surface0 = '#343e43',
        base = '#2b3438',
        mantle = '#232a2e',
        crust = '#1c2225',
      },
    },
    summer = {
      name = 'Summer',
      dark = false,
      colors = {
        red = '#c58687',
        orange = '#c69883',
        yellow = '#c4aa80',
        lime = '#abb182',
        green = '#91a77a',
        aqua = '#74a48b',
        skye = '#719f96',
        snow = '#7799a3',
        blue = '#8294ad',
        purple = '#a897b8',
        pink = '#c499b8',
        cherry = '#c29fb2',
        text = '#2b3034',
        subtext1 = '#455355',
        subtext0 = '#576869',
        overlay2 = '#707d76',
        overlay1 = '#829084',
        overlay0 = '#acb5a4',
        surface2 = '#ceccbd',
        surface1 = '#e6e1d3',
        surface0 = '#ede8dd',
        base = '#f5efe6',
        mantle = '#f2eae1',
        crust = '#e8ded5',
      },
    },
  },
}
